const express = require('express');
const fs = require('fs');
const path = require('path');
const pidusage = require('pidusage');
const mc = require('../minecraft');
const { getConfig, serverDir } = require('../config');
const { levelName } = require('../utils/backup');
const history = require('../history');
const { getLatestVersion, downloadJar } = require('../utils/jars');

const router = express.Router();

// Recently seen players: playerdata file mtimes mapped to names via usercache.json
function recentPlayers() {
  let byUuid = {};
  const uc = path.join(serverDir(), 'usercache.json');
  if (fs.existsSync(uc)) {
    try { byUuid = Object.fromEntries(JSON.parse(fs.readFileSync(uc, 'utf8')).map(p => [p.uuid, p.name])); } catch (e) { /* ignore */ }
  }
  const dir = path.join(serverDir(), levelName(), 'playerdata');
  let entries = [];
  if (fs.existsSync(dir)) {
    entries = fs.readdirSync(dir)
      .filter(f => f.endsWith('.dat'))
      .map(f => {
        const name = byUuid[f.slice(0, -4)];
        return name ? { name, lastSeen: fs.statSync(path.join(dir, f)).mtimeMs } : null;
      })
      .filter(Boolean);
  }
  const online = new Set([...mc.players].map(n => n.toLowerCase()));
  for (const p of mc.players) {
    if (!entries.some(e => e.name.toLowerCase() === p.toLowerCase())) {
      entries.push({ name: p, lastSeen: Date.now() });
    }
  }
  for (const e of entries) e.online = online.has(e.name.toLowerCase());
  entries.sort((a, b) => (b.online - a.online) || (b.lastSeen - a.lastSeen));
  return entries.slice(0, 8);
}

router.get('/overview', (req, res) => {
  res.json({ history: history.list(), recent: recentPlayers() });
});

function eulaState() {
  const file = path.join(serverDir(), 'eula.txt');
  if (!fs.existsSync(file)) return 'missing';
  return /^\s*eula\s*=\s*true\s*$/m.test(fs.readFileSync(file, 'utf8')) ? 'accepted' : 'declined';
}

router.get('/status', (req, res) => {
  const cfg = getConfig();
  res.json({
    status: mc.status,
    players: [...mc.players],
    uptime: mc.uptime,
    jarExists: fs.existsSync(path.join(serverDir(), cfg.jarFile)),
    jarFile: cfg.jarFile,
    eula: eulaState()
  });
});

router.get('/stats', async (req, res) => {
  if (!mc.pid) return res.json({ cpu: 0, memory: 0, uptime: 0, online: false });
  try {
    const s = await pidusage(mc.pid);
    res.json({ cpu: s.cpu, memory: s.memory, uptime: mc.uptime, online: true });
  } catch (e) {
    res.json({ cpu: 0, memory: 0, uptime: mc.uptime, online: true });
  }
});

router.post('/start', (req, res) => {
  if (mc.status !== 'offline') return res.status(409).json({ error: 'Server is not offline' });
  res.json({ ok: true });
  startWithUpdate().catch(e => {
    mc.pushLog(`[dashboard] ${e.message}`);
    if (mc.status === 'starting' && !mc.proc) mc.setStatus('offline');
  });
});

async function startWithUpdate() {
  const installed = getConfig().installedJar; // e.g. "vanilla 1.21.4" or ""
  if (installed) {
    const [type, version] = installed.split(' ');
    mc.setStatus('starting'); // disable Start button on the client right away
    mc.pushLog('[dashboard] Checking for updates…');
    try {
      const latest = await getLatestVersion(type);
      if (latest !== version) {
        mc.pushLog(`[dashboard] Update available: ${type} ${latest} — downloading`);
        await downloadJar(type, latest, msg => mc.pushLog(msg));
      } else {
        mc.pushLog(`[dashboard] ${installed} is up to date`);
      }
    } catch (e) {
      mc.pushLog(`[dashboard] Update check failed: ${e.message} — starting with current jar`);
    }
  }
  mc.start(getConfig()); // re-reads config so updated jarFile / installedJar is picked up
}

router.post('/stop', async (req, res) => {
  await mc.stop();
  res.json({ ok: true });
});

router.post('/restart', async (req, res, next) => {
  try {
    await mc.stop();
    mc.start(getConfig());
    res.json({ ok: true });
  } catch (e) { next(e); }
});

router.post('/command', (req, res) => {
  const { command } = req.body;
  if (!command || !command.trim()) {
    return res.status(400).json({ error: 'No command given' });
  }
  mc.sendCommand(command.trim());
  res.json({ ok: true });
});

const LOG_DIR = path.join(__dirname, '..', '..', 'console-logs');

router.get('/console-logs', (req, res) => {
  if (!fs.existsSync(LOG_DIR)) return res.json([]);
  const files = fs.readdirSync(LOG_DIR)
    .filter(f => f.endsWith('.log'))
    .map(f => {
      const st = fs.statSync(path.join(LOG_DIR, f));
      return { name: f, size: st.size, created: st.mtimeMs };
    })
    .sort((a, b) => b.created - a.created);
  res.json(files);
});

router.get('/console-logs/:name', (req, res) => {
  const name = req.params.name;
  // names are generated by the dashboard itself: console-<timestamp>-<reason>.log
  if (!/^console-[\w\-]{1,80}\.log$/.test(name)) return res.status(400).json({ error: 'Invalid log name' });
  const file = path.resolve(LOG_DIR, name);
  if (!file.startsWith(path.resolve(LOG_DIR) + path.sep) || !fs.existsSync(file)) {
    return res.status(404).json({ error: 'Log not found' });
  }
  res.download(file);
});

router.post('/eula', (req, res) => {
  fs.writeFileSync(path.join(serverDir(), 'eula.txt'), 'eula=true\n');
  res.json({ ok: true });
});

module.exports = router;
